---
spec_version: v1
config:
  enable_pull_requests_from_forks: false
  deployment_policy_branch: production
  enable_pe_plans: true

pipelines:
  main:
    triggers:
      - pull_request
      - commit
    stages:
      - name: "Lint/Parser validation"
        auto_promote: all_succeeded
        steps:
          - type: job
            name: control-repo-puppetfile-syntax-validate
          - type: job
            name: control-repo-template-syntax-validate
          - type: job
            name: control-repo-hiera-syntax-validate
          - type: job
            name: control-repo-manifest-validate

      - name: "Impact Analysis"
        auto_promote: any_succeeded
        steps:
          - type: impact_analysis
            concurrent_compilations: 10
            deployments:
              - "Direct merge to Production"
          - type: pull_request_gate

      - name: "Deploy to Production"
        auto_promote: all_succeeded
        steps:
          - type: deployment
            policy: direct_merge
            name: "Direct merge to Production"
            target:
              type: node_group
              node_group_id: 2e27a43a-d566-4e87-a0b9-ba767a760905 # All Environments, fetched from Primary "Node Groups" Tab
            pe_server: PE
            parameters:
              stop_if_nodes_fail: 10
              noop: false
              timeout: 60

  # development:
  #   triggers:
  #     - pull_request
  #     - commit
  #   stages:
  #     - name: "Lint/Parser validation"
  #       auto_promote: all_succeeded
  #       steps:
  #         - type: job
  #           name: control-repo-puppetfile-syntax-validate
  #         - type: job
  #           name: control-repo-template-syntax-validate
  #         - type: job
  #           name: control-repo-hiera-syntax-validate
  #         - type: job
  #           name: control-repo-manifest-validate

  #     - name: "Impact Analysis"
  #       auto_promote: all_succeeded
  #       steps:
  #         - type: impact_analysis
  #           concurrent_compilations: 10
  #           deployments:
  #             - "Direct merge to Production"
  #         - type: pull_request_gate

  #     - name: "Deploy to Production"
  #       auto_promote: all_succeeded
  #       steps:
  #         - type: deployment
  #           policy: direct_merge
  #           name: "Direct merge to Production"
  #           target:
  #             type: node_group
  #             node_group_id: 2e27a43a-d566-4e87-a0b9-ba767a760905 # All Environments, fetched from Primary "Node Groups" Tab
  #           pe_server: PE
  #           parameters:
  #             stop_if_nodes_fail: 10
  #             noop: false
  #             timeout: 60
