---
spec_version: v1
config:
  enable_pull_requests_from_forks: false
  deployment_policy_branch: production
  enable_pe_plans: true

pipelines:
  main:
    triggers:
    - "COMMIT"
    - "PULL_REQUEST"
    stages:
    - name: "Lint/Parser validation"
      auto_promote: all_succeeded
      steps:
      - type: job
        name: control-repo-puppetfile-syntax-validate
      - type: job
        name: control-repo-template-syntax-validate
      - type: job
        name: control-repo-hiera-syntax-validate
      - type: job
        name: control-repo-manifest-validate

    - name: "Impact Analysis"
      steps:
      - type: "IMPACT_ANALYSIS"
        deployments:
        - "Deployment to production on PE"
        concurrent_compilations: 10
        all_deployments: false
      - type: "PULL_REQUEST_GATE"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: "any_succeeded"
    - name: "Deploy to Production"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment to production on PE"
        policy:
          name: "cd4pe_deployments::direct"
        parameters:
          noop: false
          fail_if_no_nodes: true
          max_node_failure: 5
        timeout: 300000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "PE"
        target:
          type: "NODE_GROUP"
          node_group_id: "2e27a43a-d566-4e87-a0b9-ba767a760905" # All Environments
      auto_promote: "all_succeeded"
